env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
